import type { AgentHtmlTag } from "@/agent-html/ast/types"

export const layoutTags = new Set<AgentHtmlTag>([
  "Page",
  "Section",
  "Stack",
  "Cluster",
  "Grid",
])

export const allTags = new Set<AgentHtmlTag>([
  "Page",
  "Section",
  "Stack",
  "Cluster",
  "Grid",
  "Accordion",
  "AccordionItem",
  "AccordionTrigger",
  "AccordionContent",
  "Alert",
  "AlertTitle",
  "AlertDescription",
  "AlertAction",
  "AspectRatio",
  "Badge",
  "Button",
  "Card",
  "CardHeader",
  "CardTitle",
  "CardDescription",
  "CardAction",
  "CardContent",
  "CardFooter",
  "Carousel",
  "CarouselContent",
  "CarouselItem",
  "CarouselPrevious",
  "CarouselNext",
  "Progress",
  "Separator",
  "Table",
  "TableCaption",
  "TableHeader",
  "TableBody",
  "TableFooter",
  "TableRow",
  "TableHead",
  "TableCell",
  "Tabs",
  "TabsList",
  "TabsTrigger",
  "TabsContent",
  "Timeline",
  "TimelineItem",
  "TimelineTitle",
  "TimelineDescription",
  "TimelineContent",
  "Chart",
  "ChartSeries",
  "ChartTooltip",
  "CodeBlock",
  "Icon",
  "Image",
  "Text",
])

